apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
  namespace: go-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:17.5
          env:
            - name: POSTGRES_PASSWORD
              value: !
          ports: