apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: go-k8s-demo
data:
  DB_HOST: "postgres-service"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "!"
  DB_NAME: "postgres"
  DB_PORT: "5432"